#!/bin/bash
#~/.config/dunst/dunstrc
#[global]
#    font = DejaVu Sans Mono 12
#~/.config/i3/config
#bindsym button3 exec tran
#/usr/local/bin/tran
notify-send -i /usr/share/icons/gcolor_trans_32.png "$(trans -b -s en -t ru -speak -j $(xsel -o))"
